### ISSUE TITLE
Ask for name and year to fill out in license

### ISSUE THREAD

**Issue by Swimburger** [khalidabuhakmeh/ChooseALicense-Cli#1]
Currently a `[year]` and `[fullname]` placeholder is placed in the generate template.
It would be nice if the `choose-license new` command had arguments for `year` and `fullname`, and/or the command would prompt for the `year` and `fullname`.

I would pre-fill `year` with the current year, and `fullname` with the name found in their git configuration if present.

I imagine the experience would be like this:
```bash
choose-license new mit
> Enter your full name [John Doe]:
> Enter the license year [2022]: 
```

By hitting enter without providing a `fullname` or `year`, it accepts the pre-filled value.

**Comment by khalidabuhakmeh** [comment]
Fine... let me try. Is this OSS?

**Comment by Swimburger** [comment]
I can submit a PR ;)
